python train.py \
--trial 0 \
--model player_ball \
--macro_type player_poss \
--target_type ball \
--n_features 6 \
--n_players 11 \
--flip_pitch \
--macro_weight 20 \
--rloss_weight 1 \
--bidirectional \
--macro_ppe \
--macro_fpe \
--macro_fpi \
--macro_pe_dim 16 \
--macro_pi_dim 16 \
--macro_rnn_dim 256 \
--micro_pi_dim 128 \
--micro_rnn_dim 256 \
--n_epochs 50 \
--start_lr 0.0005 \
--min_lr 1e-6 \
--batch_size 64 \
--print_batch 50 \
--save_epoch 50